server:
  port: 7007

spring:
  application:
    name: bms-web

  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: root
    driverClassName: org.h2.Driver
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2

mybatis-plus:
  global-config:
    db-config:
      # 设置逻辑删除字段
      logic-delete-field: isDelete